### PR TITLE
Use StealJS for example and test

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by blink1073** [comment]
Do we want to include `http-server` and a `npm run serve` script for the example?

**Comment by sccolbert** [comment]
sure `npm run serve:example`

**Comment by blink1073** [comment]
Well, as it stands, the example is it's own entity, you have to `cd example` and run the appropriate commands.

**Comment by sccolbert** [comment]
ah, okay

**Comment by sccolbert** [comment]
should we close this in lieu of #9?

**Comment by blink1073** [comment]
I don't like this because of the relative install in `example/package.json`.  If we were to use `Steal`, we should bundle it and use `production` mode.

**Comment by sccolbert** [comment]
So, close it then?

**Pull request closed without merging**
